###############################################################################
## Copyright (C) 2020-2023 Analog Devices, Inc. All rights reserved.
### SPDX short identifier: ADIBSD
###############################################################################

#
## mxfe
#

set_property -dict {PACKAGE_PIN P11 IOSTANDARD LVCMOS18} [get_ports {agc0[0]}]
set_property -dict {PACKAGE_PIN N11 IOSTANDARD LVCMOS18} [get_ports {agc0[1]}]
set_property -dict {PACKAGE_PIN N9 IOSTANDARD LVCMOS18} [get_ports {agc1[0]}]
set_property -dict {PACKAGE_PIN N8 IOSTANDARD LVCMOS18} [get_ports {agc1[1]}]
set_property -dict {PACKAGE_PIN N13 IOSTANDARD LVCMOS18} [get_ports {agc2[0]}]
set_property -dict {PACKAGE_PIN M13 IOSTANDARD LVCMOS18} [get_ports {agc2[1]}]
set_property -dict {PACKAGE_PIN P12 IOSTANDARD LVCMOS18} [get_ports {agc3[0]}]
set_property -dict {PACKAGE_PIN N12 IOSTANDARD LVCMOS18} [get_ports {agc3[1]}]
set_property IOSTANDARD LVDS [get_ports clkin10_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports clkin10_n]
set_property DQS_BIAS TRUE [get_ports clkin10_n]
set_property PACKAGE_PIN Y4 [get_ports clkin10_p]
set_property PACKAGE_PIN Y3 [get_ports clkin10_n]
set_property IOSTANDARD LVDS [get_ports clkin10_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports clkin10_p]
set_property DQS_BIAS TRUE [get_ports clkin10_p]
set_property IOSTANDARD LVDS [get_ports clkin6_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports clkin6_n]
set_property DQS_BIAS TRUE [get_ports clkin6_n]
set_property PACKAGE_PIN T8 [get_ports clkin6_p]
set_property PACKAGE_PIN R8 [get_ports clkin6_n]
set_property IOSTANDARD LVDS [get_ports clkin6_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports clkin6_p]
set_property DQS_BIAS TRUE [get_ports clkin6_p]
set_property -dict {PACKAGE_PIN G7} [get_ports fpga_refclk_in_n]
set_property -dict {PACKAGE_PIN G8} [get_ports fpga_refclk_in_p]
set_property -dict {PACKAGE_PIN F1} [get_ports {rx_data_n[2]}]
set_property -dict {PACKAGE_PIN F2} [get_ports {rx_data_p[2]}]
set_property -dict {PACKAGE_PIN H1} [get_ports {rx_data_n[0]}]
set_property -dict {PACKAGE_PIN H2} [get_ports {rx_data_p[0]}]
set_property -dict {PACKAGE_PIN K1} [get_ports {rx_data_n[3]}]
set_property -dict {PACKAGE_PIN K2} [get_ports {rx_data_p[3]}]
set_property -dict {PACKAGE_PIN J3} [get_ports {rx_data_n[1]}]
set_property -dict {PACKAGE_PIN J4} [get_ports {rx_data_p[1]}]
set_property -dict {PACKAGE_PIN G3} [get_ports {tx_data_n[0]}]
set_property -dict {PACKAGE_PIN G4} [get_ports {tx_data_p[0]}]
set_property -dict {PACKAGE_PIN F5} [get_ports {tx_data_n[2]}]
set_property -dict {PACKAGE_PIN F6} [get_ports {tx_data_p[2]}]
set_property -dict {PACKAGE_PIN H5} [get_ports {tx_data_n[1]}]
set_property -dict {PACKAGE_PIN H6} [get_ports {tx_data_p[1]}]
set_property -dict {PACKAGE_PIN K5} [get_ports {tx_data_n[3]}]
set_property -dict {PACKAGE_PIN K6} [get_ports {tx_data_p[3]}]
set_property IOSTANDARD LVDS [get_ports fpga_syncin_0_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports fpga_syncin_0_n]
set_property PACKAGE_PIN V2 [get_ports fpga_syncin_0_p]
set_property PACKAGE_PIN V1 [get_ports fpga_syncin_0_n]
set_property IOSTANDARD LVDS [get_ports fpga_syncin_0_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports fpga_syncin_0_p]
set_property -dict {PACKAGE_PIN Y1 IOSTANDARD LVCMOS18} [get_ports fpga_syncin_1_n]
set_property -dict {PACKAGE_PIN Y2 IOSTANDARD LVCMOS18} [get_ports fpga_syncin_1_p]
set_property -dict {PACKAGE_PIN AC4 IOSTANDARD LVDS} [get_ports fpga_syncout_0_n]
set_property -dict {PACKAGE_PIN AB4 IOSTANDARD LVDS} [get_ports fpga_syncout_0_p]
set_property -dict {PACKAGE_PIN AC1 IOSTANDARD LVCMOS18} [get_ports fpga_syncout_1_n]
set_property -dict {PACKAGE_PIN AC2 IOSTANDARD LVCMOS18} [get_ports fpga_syncout_1_p]
set_property -dict {PACKAGE_PIN Y10 IOSTANDARD LVCMOS18} [get_ports {gpio[0]}]
set_property -dict {PACKAGE_PIN Y9 IOSTANDARD LVCMOS18} [get_ports {gpio[1]}]
set_property -dict {PACKAGE_PIN L13 IOSTANDARD LVCMOS18} [get_ports {gpio[2]}]
set_property -dict {PACKAGE_PIN K13 IOSTANDARD LVCMOS18} [get_ports {gpio[3]}]
set_property -dict {PACKAGE_PIN AB8 IOSTANDARD LVCMOS18} [get_ports {gpio[4]}]
set_property -dict {PACKAGE_PIN AC8 IOSTANDARD LVCMOS18} [get_ports {gpio[5]}]
set_property -dict {PACKAGE_PIN AC7 IOSTANDARD LVCMOS18} [get_ports {gpio[6]}]
set_property -dict {PACKAGE_PIN AC6 IOSTANDARD LVCMOS18} [get_ports {gpio[7]}]
set_property -dict {PACKAGE_PIN Y12 IOSTANDARD LVCMOS18} [get_ports {gpio[8]}]
set_property -dict {PACKAGE_PIN AA12 IOSTANDARD LVCMOS18} [get_ports {gpio[9]}]
set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS18} [get_ports {gpio[10]}]
set_property -dict {PACKAGE_PIN AB5 IOSTANDARD LVCMOS18} [get_ports hmc_gpio1]
set_property -dict {PACKAGE_PIN U4 IOSTANDARD LVCMOS18} [get_ports hmc_sync]
set_property -dict {PACKAGE_PIN V4 IOSTANDARD LVCMOS18} [get_ports {irqb[0]}]
set_property -dict {PACKAGE_PIN V3 IOSTANDARD LVCMOS18} [get_ports {irqb[1]}]
set_property -dict {PACKAGE_PIN U5 IOSTANDARD LVCMOS18} [get_ports rstb]
set_property -dict {PACKAGE_PIN W5 IOSTANDARD LVCMOS18} [get_ports {rxen[0]}]
set_property -dict {PACKAGE_PIN W4 IOSTANDARD LVCMOS18} [get_ports {rxen[1]}]
set_property -dict {PACKAGE_PIN AB3 IOSTANDARD LVCMOS18} [get_ports spi0_csb]
set_property -dict {PACKAGE_PIN AC3 IOSTANDARD LVCMOS18} [get_ports spi0_miso]
set_property -dict {PACKAGE_PIN AA2 IOSTANDARD LVCMOS18} [get_ports spi0_mosi]
set_property -dict {PACKAGE_PIN AA1 IOSTANDARD LVCMOS18} [get_ports spi0_sclk]
set_property -dict {PACKAGE_PIN W7 IOSTANDARD LVCMOS18} [get_ports spi1_csb]
set_property -dict {PACKAGE_PIN AB6 IOSTANDARD LVCMOS18} [get_ports spi1_sclk]
set_property -dict {PACKAGE_PIN W6 IOSTANDARD LVCMOS18} [get_ports spi1_sdio]
set_property IOSTANDARD LVDS [get_ports sysref2_n]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref2_n]
set_property DQS_BIAS TRUE [get_ports sysref2_n]
set_property PACKAGE_PIN AA7 [get_ports sysref2_p]
set_property PACKAGE_PIN AA6 [get_ports sysref2_n]
set_property IOSTANDARD LVDS [get_ports sysref2_p]
set_property DIFF_TERM_ADV TERM_100 [get_ports sysref2_p]
set_property DQS_BIAS TRUE [get_ports sysref2_p]
set_property -dict {PACKAGE_PIN W2 IOSTANDARD LVCMOS18} [get_ports {txen[0]}]
set_property -dict {PACKAGE_PIN W1 IOSTANDARD LVCMOS18} [get_ports {txen[1]}]




