apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hdl-project-adv7513-de10nano
  title: ADV7513_DE10NANO HDL project
  description: ADV7513_DE10NANO HDL project
  version: main
  classification: software
  license:
  - ADI BSD License
  annotations:
    backstage.io/source-location: url:https://github.com/analogdevicesinc/hdl/tree/main/projects/adv7513/de10nano
  tags:
  - de10nano
  - hdl
  - project
  - reference-design
  links: []
spec:
  owner: group:default/hdl-sw-team
  type: source
  lifecycle: sustain
